name: opensearch
services:

  opensearch:
    image: opensearchproject/opensearch:latest
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=P@ssw0rd
    ports: 
      - 9200:9200
      - 9600:9600 
  volumes:
  - opensearch-data:/usr/share/opensearch/data