name: keycloak
services:
    keycloak:
        build:
            dockerfile: DockerFile.keycloak
            context: .
        ports:
        - 8081:8080
        environment:
        - KEYCLOAK_ADMIN=admin
        - KEYCLOAK_ADMIN_PASSWORD=P@ssw0rd
        - KEYCLOAK_IMPORT=./local-dev-realm.json
        volumes:
        - keycloak-data:/opt/keycloak/data
        command: start-dev --import-realm